defaults: &defaults
  cool:
    saweet: nested settings
  neat_setting: 24
  awesome_setting: <%= "Did you know 5 + 5 = 10?" %>
  google_map:
    server: http://maps.googleapis.com
    api_key: AIzaSyBrp5OKFAdzY1xre8m-Fbq3VuoswPv2Y7s

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults

cucumber:
  <<: *defaults
